version: '3'

services:
  mongo:
    image: synergatika/mongodb
    container_name: pritunldb
    hostname: pritunldb
    network_mode: bridge
    volumes:
      - ../db:/data/db

  pritunl:
    image: docker-pritunl
    container_name: pritunl
    hostname: pritunl
    network_mode: bridge
    privileged: true
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
    links:
      - mongo
    volumes:
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 88:80
      - 444:443
      - 1194:1194
      - 1194:1194/udp
    environment:
      - TZ=UTC
      - PRITUNL_DEBUG=true
      - PRITUNL_OPTS=''